export const WELCOME_SCREEN = "WELCOME_SCREEN";
export const ILLUSTRATION_RADIO_BUTTONS = "ILLUSTRATION_RADIO_BUTTONS";
export const QUSETION_ANSWER = "QUSETION_ANSWER";
export const ILLUSTRATION = "ILLUSTRATION";
